SET @DBNAME = 'alx_book_store';

SET @TABLE_NAME = (
    SELECT TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = @DBNAME
    AND TABLE_NAME = 'Books'
);

SET @SQL_QUERY = CONCAT(
    'SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA ',
    'FROM INFORMATION_SCHEMA.COLUMNS ',
    'WHERE TABLE_SCHEMA = "', @DBNAME, '" ',
    'AND TABLE_NAME = "', @TABLE_NAME, '"'
);

PREPARE STMT FROM @SQL_QUERY;
EXECUTE STMT;
DEALLOCATE PREPARE STMT;
